pricing.endpoint=http://localhost:8082
maps.endpoint=http://localhost:9191
spring.jpa.defer-datasource-initialization=true
spring.h2.console.settings.web-allow-others=true
# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.show-actuator=false
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
# HATEOAS Configuration for Swagger
springdoc.show-openapi-endpoints=false
springdoc.model-converters-to-disable=io.swagger.v3.plugins.converters.models.ModelConverterImpl